image: instituteforsoftware/coast-build:latest

variables:
  PYPIRC_LOCATION: $CI_PROJECT_DIR/.pypirc

before_script:
- echo -e "[distutils]\\nindex-servers =\\n  pypi\\n  testpypi\\n[pypi]\\n#repository:$PYPI_REPOSITORY\\nusername:$PYPI_USERNAME\\npassword:$PYPI_PASSWORD\\n[testpypi]\\nrepository:$PYPI_TEST_REPOSITORY\\nusername:$PYPI_TEST_USERNAME\\npassword:$PYPI_TEST_PASSWORD\\n" >$PYPIRC_LOCATION
- echo -e "[pytest]\\nlog_cli = 1\\nlog_cli_level = ERROR\\nlog_file = pytest.log\\nlog_file_level = DEBUG\\n" >$CI_PROJECT_DIR/pytest.ini
- type -fP tox || pip install tox

build:
  stage: build
  tags:
  - docker
  script:
  - tox --recreate -e wheel --result-json "$(pwd)/$CI_JOBNAME.tox.log"

test and deploy to testpypi:
  stage: test
  tags:
  - docker
  variables:
    PYPI_REPO_NAME: testpypi
  artifacts:
    paths:
    - dist/*.whl
    - dist/*.tar.gz
  script:
  - tox --recreate --result-json "$(pwd)/$CI_JOBNAME.tox.log"
  - tox --recreate -e upload --result-json "$(pwd)/$CI_JOBNAME.upload.tox.log"

deploy to pypi:
  stage: deploy
  tags:
  - docker
  variables:
    PYPI_REPO_NAME: pypi
  only:
  - tags
  - triggers
  when: manual
  dependencies: []
  artifacts:
    paths:
    - dist/*.whl
    - dist/*.tar.gz
  script:
  - tox --recreate -e upload --result-json "$(pwd)/$CI_JOBNAME.tox.log"
