image: instituteforsoftware/coast-build:latest

variables:
  PYPIRC_LOCATION: $CI_PROJECT_DIR/.pypirc

before_script:
- echo -e "[distutils]\\nindex-servers =\\n  pypi\\n  testpypi\\n[pypi]\\n#repository:$PYPI_REPOSITORY\\nusername:$PYPI_USERNAME\\npassword:$PYPI_PASSWORD\\n[testpypi]\\nrepository:$PYPI_TEST_REPOSITORY\\nusername:$PYPI_TEST_USERNAME\\npassword:$PYPI_TEST_PASSWORD\\n" >$PYPIRC_LOCATION

build:
  stage: build
  tags:
  - docker
  script:
  - tox2 --recreate -e wheel

test deployment to testpypi:
  stage: test
  tags:
  - docker
  variables:
    PYPI_REPO_NAME: testpypi
  artifacts:
    paths:
    - dist/*.whl
    - dist/*.tar.gz
  script:
  - tox2 --recreate
  - tox2 --recreate -e upload

deploy to pypi:
  stage: deploy
  tags:
  - docker
  variables:
    PYPI_REPO_NAME: pypi
  only:
  - tags
  - triggers
  when: manual
  dependencies: []
  artifacts:
    paths:
    - dist/*.whl
    - dist/*.tar.gz
  script:
  - tox2 --recreate -e upload
