image: instituteforsoftware/coast-build:latest

variables:
  PYPIRC_LOCATION: $CI_PROJECT_DIR/.pypirc

before_script:
- echo -e "[distutils]\\nindex-servers =\\n  pypi\\n  testpypi\\n[pypi]\\n#repository:$PYPI_REPOSITORY\\nusername:$PYPI_USERNAME\\npassword:$PYPI_PASSWORD\\n[testpypi]\\nrepository:$PYPI_TEST_REPOSITORY\\nusername:$PYPI_TEST_USERNAME\\npassword:$PYPI_TEST_PASSWORD\\n" >$PYPIRC_LOCATION
- type -fP tox || pip install tox

build:
  stage: build
  tags:
  - docker
  artifacts:
    expire_in: 1 day
    paths:
    - "*.tox.json"
    - pytest.log
  script:
  - tox --recreate -e wheel --result-json "$(pwd)/$CI_JOB_NAME.tox.json"

test:
  stage: test
  tags:
  - docker
  variables:
    PYPI_REPO_NAME: testpypi
  artifacts:
    expire_in: 1 day
    paths:
    - dist/*.whl
    - dist/*.tar.gz
    - "*.tox.json"
    - pytest.log
    - testresults.xml
    - coverage/report.xml
  script:
  - tox --recreate --result-json "$(pwd)/$CI_JOB_NAME.tox.json"

deploy to testpypi:
  stage: deploy
  tags:
  - docker
  only:
    refs:
    - develop
  variables:
    PYPI_REPO_NAME: testpypi
  artifacts:
    expire_in: 1 day
    paths:
    - dist/*.whl
    - dist/*.tar.gz
    - "*.tox.json"
    - pytest.log
    - testresults.xml
    - coverage/report.xml
  script:
  - tox --recreate -e upload --result-json "$(pwd)/$CI_JOB_NAME.deploy.tox.json"

deploy to pypi:
  stage: deploy
  tags:
  - docker
  variables:
    PYPI_REPO_NAME: pypi
  only:
  - tags
  - triggers
  when: manual
  dependencies: []
  artifacts:
    expire_in: 1 day
    paths:
    - dist/*.whl
    - dist/*.tar.gz
    - "*.tox.json"
    - pytest.log
  script:
  - tox --recreate -e upload --result-json "$(pwd)/$CI_JOB_NAME.deploy.tox.json"
