import SConsider
print('get_sconstruct_dir='+SConsider.get_sconstruct_dir(SConsider.baseEnv).get_abspath())
print('get_launch_dir='+SConsider.get_launch_dir(SConsider.baseEnv).get_abspath())
print('base_out_dir='+SConsider.baseEnv.getBaseOutDir().get_abspath())
